service:
  name: boffa

package:
    artifact: .build/lambda/HelloWorld/lambda.zip

# plugins:
#   - serverless-bundle
#   - serverless-pseudo-parameters

provider:
    name: aws
    runtime: provided
    stage: ${opt:stage, 'dev'}
    region: eu-north-1
    iamRoleStatements:
        - Effect: Allow
          Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
          Resource: "*"
  
functions:
  hello:
    handler: HelloWorld
    events:
      - http:
          method: POST
          path: /hello
          integration: LAMBDA
